language: julia

julia:
  - nightly

env:
    global:
        - SSH_KEY="travis_key"
        - GIT_NAME="Frieda Rong"
        - GIT_EMAIL="adeirff@gmail.com"
        - SOURCE_DIR="public"
        - DEPLOY_BRANCH="master"

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_372990b028ab_key -iv $encrypted_372990b028ab_iv
  -in travis_key.enc -out travis_key -d

install:

script:
    - julia -e 'Pkg.add("JSON")'
    - julia -e 'Pkg.clone("https://github.com/TotalVerb/English.jl")'
    - julia -e 'Pkg.add("DataStructures")'
    - julia -e 'Pkg.clone("https://github.com/TotalVerb/SExpressions.jl")'
    - julia make.jl

after_success:
    - ./deploy.sh
